from .test_instant_decay import SnnInstantDecayTests, DsInstantDecayTests
from .test_instant_decay import PynnSpinnakerInstantDecayTests, PynnBrianInstantDecayTests
from .test_vector_input import SnnVectorInputTests, DsVectorInputTests
from .test_vector_input import PynnSpinnakerVectorInputTests, PynnBrianVectorInputTests
from .test_neuron_params import SnnChangeNeuronPropertyTests, DsChangeNeuronPropertyTests
from .test_neuron_params import PynnSpinnakerChangeNeuronPropertyTests, PynnBrianChangeNeuronPropertyTests
from .test_synapse_params import SnnChangeSynapsePropertyTests, DsChangeSynapsePropertyTests
from .test_synapse_params import PynnSpinnakerChangeSynapsePropertyTests, PynnBrianChangeSynapsePropertyTests
