from .test_instant_decay import SnnInstantDecayTests, DsInstantDecayTests
from .test_instant_decay import PynnSpinnakerInstantDecayTests
from .test_vector_input import SnnVectorInputTests, DsVectorInputTests
from .test_vector_input import PynnSpinnakerVectorInputTests
from .test_neuron_params import SnnChangeNeuronPropertyTests, DsChangeNeuronPropertyTests
from .test_neuron_params import PynnSpinnakerChangeNeuronPropertyTests
from .test_synapse_params import SnnChangeSynapsePropertyTests, DsChangeSynapsePropertyTests
from .test_synapse_params import PynnSpinnakerChangeSynapsePropertyTests
