import unittest

from .test_core import SnnInstantDecayTests, DsInstantDecayTests
from .test_core import PynnSpinnakerInstantDecayTests, PynnBrianInstantDecayTests
from .test_core import SnnVectorInputTests, DsVectorInputTests
from .test_core import PynnSpinnakerVectorInputTests, PynnBrianVectorInputTests
from .test_core import SnnChangeNeuronPropertyTests, DsChangeNeuronPropertyTests
from .test_core import PynnSpinnakerChangeNeuronPropertyTests, PynnBrianChangeNeuronPropertyTests
from .test_core import SnnChangeSynapsePropertyTests, DsChangeSynapsePropertyTests
from .test_core import PynnSpinnakerChangeSynapsePropertyTests, PynnBrianChangeSynapsePropertyTests
from .test_utility_bricks import SnnAdderTests, DsAdderTests
from .test_utility_bricks import PynnSpinnakerAdderTests, PynnBrianAdderTests
from .test_utility_bricks import SnnRegisterTests, DsRegisterTests
from .test_utility_bricks import PynnSpinnakerRegisterTests, PynnBrianRegisterTests
from .test_app_bricks import SnnLISTests, DsLISTests
from .test_app_bricks import PynnSpinnakerLISTests, PynnBrianLISTests
from .test_stochastic_bricks import SnnThresholdTests, DsThresholdTests
#from test_graph_bricks import SnnGraphTests, DsGraphTests, PynnSpinnakerGraphTests

loader = unittest.TestLoader()

snn_suite = unittest.TestSuite()
snn_suite.addTest(loader.loadTestsFromTestCase(SnnInstantDecayTests))
snn_suite.addTest(loader.loadTestsFromTestCase(SnnVectorInputTests))
snn_suite.addTest(loader.loadTestsFromTestCase(SnnChangeNeuronPropertyTests))
snn_suite.addTest(loader.loadTestsFromTestCase(SnnChangeSynapsePropertyTests))
snn_suite.addTest(loader.loadTestsFromTestCase(SnnAdderTests))
snn_suite.addTest(loader.loadTestsFromTestCase(SnnRegisterTests))
snn_suite.addTest(loader.loadTestsFromTestCase(SnnLISTests))
snn_suite.addTest(loader.loadTestsFromTestCase(SnnThresholdTests))

ds_suite = unittest.TestSuite()
ds_suite.addTest(loader.loadTestsFromTestCase(DsInstantDecayTests))
ds_suite.addTest(loader.loadTestsFromTestCase(DsVectorInputTests))
ds_suite.addTest(loader.loadTestsFromTestCase(DsChangeNeuronPropertyTests))
ds_suite.addTest(loader.loadTestsFromTestCase(DsChangeSynapsePropertyTests))
ds_suite.addTest(loader.loadTestsFromTestCase(DsAdderTests))
ds_suite.addTest(loader.loadTestsFromTestCase(DsRegisterTests))
ds_suite.addTest(loader.loadTestsFromTestCase(DsLISTests))
ds_suite.addTest(loader.loadTestsFromTestCase(DsThresholdTests))

pynn_spinnaker_suite = unittest.TestSuite()
pynn_spinnaker_suite.addTest(loader.loadTestsFromTestCase(PynnSpinnakerInstantDecayTests))
pynn_spinnaker_suite.addTest(loader.loadTestsFromTestCase(PynnSpinnakerVectorInputTests))
pynn_spinnaker_suite.addTest(loader.loadTestsFromTestCase(PynnSpinnakerChangeNeuronPropertyTests))
#pynn_spinnaker_suite.addTest(loader.loadTestsFromTestCase(PynnSpinnakerChangeSynapsePropertyTests))
pynn_spinnaker_suite.addTest(loader.loadTestsFromTestCase(PynnSpinnakerAdderTests))
pynn_spinnaker_suite.addTest(loader.loadTestsFromTestCase(PynnSpinnakerRegisterTests))
pynn_spinnaker_suite.addTest(loader.loadTestsFromTestCase(PynnSpinnakerLISTests))

pynn_brian_suite = unittest.TestSuite()
pynn_brian_suite.addTest(loader.loadTestsFromTestCase(PynnBrianInstantDecayTests))
pynn_brian_suite.addTest(loader.loadTestsFromTestCase(PynnBrianVectorInputTests))
pynn_brian_suite.addTest(loader.loadTestsFromTestCase(PynnBrianChangeNeuronPropertyTests))
#pynn_brian_suite.addTest(loader.loadTestsFromTestCase(PynnBrianChangeSynapsePropertyTests))
pynn_brian_suite.addTest(loader.loadTestsFromTestCase(PynnBrianAdderTests))
pynn_brian_suite.addTest(loader.loadTestsFromTestCase(PynnBrianRegisterTests))
pynn_brian_suite.addTest(loader.loadTestsFromTestCase(PynnBrianLISTests))
