stages:
  - test
  - deploy

tests:
  stage: test
  image: cee-gitlab.sandia.gov:4567/srberna/python:3.9
  before_script:
    - python -m pip install -r requirements.txt
    - python -m pip install --upgrade .
    - python -m pip install pytest
  script:
    - pytest

pages:
  stage: deploy
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx furo
  script:
    - cd docs && make html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
