default:
  image: cee-gitlab.sandia.gov:4567/srberna/python:3.9

stages:
  - linting
  - testing
  - build
  - deploy

isort:
  stage: linting
  before_script:
    - python -m pip install -r requirements.txt
    - python -m pip install --upgrade .
    - python -m pip install isort
  script:
    - isort --check --filter-files tests fugu/utils/validation.py fugu/simulators
  rules:
    - when: always

black:
  stage: linting
  before_script:
    - python -m pip install -r requirements.txt
    - python -m pip install --upgrade .
    - python -m pip install black
  script:
    - black --check tests fugu/utils/validation.py fugu/simulators --exclude="(tests/unit/bricks/)"
  rules:
    - when: always

tests:
  stage: testing
  before_script:
    - python -m pip install .[whetstone]
    - python -m pip install --upgrade .
    - python -m pip install pytest==7.4.4
  script:
    - pytest
  rules:
    - when: always

coverage:
  stage: testing
  before_script:
    - python -m pip install .[whetstone]
    - python -m pip install --upgrade .
    - python -m pip install pytest==7.4.4 coverage==7.4.1
  script:
    - |
      coverage run -m pytest
      echo "Report generated with command: coverage report -m --skip-covered" > coverage_report.txt
      echo >> coverage_report.txt
      coverage report -m --skip-covered >> coverage_report.txt
  artifacts:
    paths:
      - coverage_report.txt
    when: on_success
  rules:
    - when: always

pages_build_on_mr:
  stage: build
  image: cee-gitlab.sandia.gov:4567/srberna/python:3.9
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx_rtd_theme sphinx furo
  script:
    - cd docs && make html
  rules:
    - when: always

pages:
  stage: deploy
  image: cee-gitlab.sandia.gov:4567/srberna/python:3.9
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx_rtd_theme sphinx furo
  script:
    - cd docs && make html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
