default:
  image: cee-gitlab.sandia.gov:4567/srberna/python:3.9

stages:
  - linting
  - testing
  - build
  - deploy

isort:
  stage: linting
  before_script:
    - python -m pip install -r requirements.txt
    - python -m pip install --upgrade .
    - python -m pip install isort
  script:
    - isort --check --skip=__init__.py --skip=tests/unit/utils/test_validation.py --filter-files tests fugu/utils/validation.py fugu/simulators

black:
  stage: linting
  before_script:
    - python -m pip install -r requirements.txt
    - python -m pip install --upgrade .
    - python -m pip install black
  script:
    - black --check tests fugu/utils/validation.py fugu/simulators

tests:
  stage: testing
  before_script:
    - python -m pip install -r requirements.txt
    - python -m pip install --upgrade .
    - python -m pip install pytest
  script:
    - pytest

coverage:
  stage: testing
  before_script:
    - python -m pip install -r requirements.txt
    - python -m pip install --upgrade .
    - python -m pip install pytest coverage
  script:
    - |
      coverage run -m pytest
      echo "Report generated with command: coverage report -m --skip-covered" > coverage_report.txt
      echo >> coverage_report.txt
      coverage report -m --skip-covered >> coverage_report.txt
  artifacts:
    paths:
      - coverage_report.txt
    when: on_success

pages_build_on_mr:
  stage: build
  image: cee-gitlab.sandia.gov:4567/srberna/python:3.9
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx_rtd_theme sphinx furo
  script:
    - cd docs && make html
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  image: cee-gitlab.sandia.gov:4567/srberna/python:3.9
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx_rtd_theme sphinx furo
  script:
    - cd docs && make html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
