stages:
  - build
  - deploy

pages_build_on_mr:
  stage: build
  image: cee-gitlab.sandia.gov:4567/srberna/python:3.9
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx_rtd_theme sphinx furo
  script:
    - cd docs && make html
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  image: cee-gitlab.sandia.gov:4567/srberna/python:3.9
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx_rtd_theme sphinx furo
  script:
    - cd docs && make html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
