variables:
  http_proxy: "http://wwwproxy.sandia.gov:80/"
  https_proxy: "http://wwwproxy.sandia.gov:80/"
  no_proxy: "127.0.0.1,localhost,.sandia.gov"

stages:
    - test

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .cache/pip

before_script:
    - python3 -V
    - python2 -V
    - pip3 install -r requirements3.txt
    - pip2 install -r requirements2.txt

main_tests:
    image: python:3.6
    stage: test
    script:
        - python3 -m unittest -f test.test_suites.ds_suite
        - python3 -m unittest -f test.test_suites.snn_suite
    tags:
        - docker

pynn_tests:
    image: python:2.7
    stage: test
    script:
        - python2 -m unittest -f test.test_suites.pynn_brian_suite
    tags:
        - docker
