[tox]
requires = tox-conda
envlist = py39, py310, py311, py310-networkx{26,27,28}
isolated_build = True
package = editable

[testenv]
passenv = *
deps = .[whetstone,dev,examples,networkx24]
commands = pytest -v --maxfail=10

[testenv:py39]
conda-deps =
    python=3.9

[testenv:py39-networkx32]
conda-deps =
    python=3.10
deps =
    networkx32: .[dev,examples]

[testenv:py39-tensorflow18-networkx32]
setenv =
    EXCLUDE_DEPENDENCIES = six,furo,pytz,msgpack,greenlet,dateutil,future,decorator
conda-deps =
    python=3.9
deps =
    tensorflow18: .[whetstone,dev,examples]

[testenv:py310]
conda-deps =
    python=3.10

[testenv:py310-networkx32]
conda-deps =
    python=3.10
deps =
    networkx32: .[dev,examples]

[testenv:py310-tensorflow18-networkx32]
conda-deps =
    python=3.10
deps =
    tensorflow18: .[whetstone,dev,examples]

[testenv:py311-tensorflow18-networkx32]
setenv =
    EXCLUDE_DEPENDENCIES = six,furo,pytz,msgpack,greenlet,dateutil,future,decorator
conda-deps =
    python=3.11
deps =
    tensorflow18: .[whetstone,dev,examples]

[testenv:py311-tensorflow18-networkx34]
setenv =
    INCLUDE_DEPENDENCIES = networkx==3.4.2
    EXCLUDE_DEPENDENCIES = six,furo,pytz,msgpack,greenlet,dateutil,future,decorator,networkx
conda-deps =
    python=3.11
deps =
    tensorflow18: .[whetstone,dev,examples]

