from .test_adder_brick import SnnAdderTests, DsAdderTests
from .test_adder_brick import PynnSpinnakerAdderTests, PynnBrianAdderTests
from .test_register_brick import SnnRegisterTests, DsRegisterTests
from .test_register_brick import PynnSpinnakerRegisterTests, PynnBrianRegisterTests
